package continuations

import continuations.Suspend.CompilerRewriteUnsuccessfulException

sealed trait Suspend:
  def continuation[A](f: Continuation[A] => Unit): A

  extension (s: Suspend)
    inline def shift[A](f: Continuation[A] => Unit): A =
      throw CompilerRewriteUnsuccessfulException

object Suspend:
  private[continuations] case object CompilerRewriteUnsuccessfulException
      extends Exception(
        """|
           |  The body of this method should have been generated by the continuations-plugin.
           |  Please open an issue so we can fix this:
           |  https://github.com/47deg/TBD/issues/new?assignees=&labels=bug&template=compilerrewriteunsuccessfulexception-bug-report.md&title=CompilerRewriteUnsuccessfulException+Bug""".stripMargin)

  given Suspend = Marker

object Marker extends Suspend:
  override def continuation[A](f: Continuation[A] => Unit): A =
    ???
