addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.5")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.4.3")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.2.24")
addSbtPlugin("com.alejandrohdezma" %% "sbt-github" % "0.11.1")
addSbtPlugin("com.alejandrohdezma" % "sbt-github-mdoc" % "0.11.1")
